# Generated by Django 4.1.2 on 2022-10-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jogo_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jogo',
            new_name='Game',
        ),
    ]
